In [3]:
import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize
import readability
import torch                                        # root package
from torch.utils.data import Dataset, DataLoader # dataset representation and loading
from torch.nn import CosineSimilarity

In [33]:
OpenFoodFacts_Demo = pd.read_csv("OpenFoodFacts_Head_Demo.csv")
OpenFoodFacts_Demo.fillna({'product_name':"Unknown"}, inplace=True)
OpenFoodFacts_Demo = OpenFoodFacts_Demo.dropna(subset = ['ingredients_text'])
print(OpenFoodFacts_Demo['ingredients_text'])

0      beta alanine, creatine hcl, ancient peat & app...
1      Bananas, vegetable oil (coconut oil, corn oil ...
2      Peanuts, wheat flour, sugar, rice flour, tapio...
3      Organic hazelnuts, organic cashews, organic wa...
4                                        Organic polenta
                             ...                        
485    Strawberries, corn syrup, high fructose corn s...
486                         Durum wheat semolina, water.
487    Tomatoes, onions, water, canola oil, garlic, g...
488    Water, organic whole soybeans, calcium sulfate...
489    Glucose syrup, water, alcohol, rice, corn syru...
Name: ingredients_text, Length: 433, dtype: object


In [5]:
>>> input1 = "I love chocolate"
>>> input2 = "I also love chocolate"
>>> cos = CosineSimilarity(dim=1, eps=1e-6)
>>> output = cos(input1, input2)

print(output)

tensor([ 0.0421, -0.1831,  0.0997, -0.0056,  0.0348, -0.0568, -0.0267, -0.0258,
         0.0711,  0.0261,  0.0586, -0.0618, -0.0437, -0.0519,  0.0326, -0.0370,
         0.0336, -0.0124, -0.0507,  0.0420, -0.0565,  0.0254, -0.0287,  0.1451,
         0.1552,  0.1225, -0.0591,  0.0529, -0.0622,  0.1089,  0.1155, -0.0223,
        -0.0032, -0.0523, -0.0394,  0.0223,  0.1974, -0.0603, -0.1029,  0.0272,
        -0.0417,  0.0018, -0.0160, -0.0496,  0.0568,  0.1283, -0.0829,  0.0099,
        -0.0486,  0.0540, -0.0437,  0.0201, -0.0007,  0.0118,  0.0473,  0.1398,
         0.0057,  0.0024, -0.0488, -0.1488,  0.0463,  0.1544, -0.1009,  0.0684,
         0.1138,  0.0116, -0.1526,  0.0004, -0.0157, -0.0063,  0.0352,  0.0401,
         0.0751,  0.1183,  0.0827,  0.1480,  0.0863, -0.0890,  0.0934, -0.1109,
         0.0502,  0.0627,  0.0343, -0.0988,  0.0694, -0.0728,  0.0017,  0.0296,
        -0.0693, -0.0101,  0.0193,  0.0017,  0.0941,  0.1043,  0.0451, -0.1996,
        -0.1371,  0.0950, -0.0169, -0.02

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity


In [34]:
ingredient_lists = {}
for index,row in OpenFoodFacts_Demo.iterrows():
    ingredient_lists[row['code']] = row['ingredients_text']
    
documents = list(ingredient_lists.values()) 
print(documents)

["beta alanine, creatine hcl, ancient peat & apple extract (as elevatp), l-leucine, l-isoleucine, l-valine, betaine anhydrous, arginine silicate inositol (as nitrosigine), cordyceps militaris (cordyceps), ganoderma lucidum (reishi), pleurotus eryngii (king trumpet), lentinula edodes (shitake), hericium erinaceus (lion's mane), and trametes veriscolor (turkey tail) (as peako2), phyllanthus emblica (fruit) extract (as capros), nattokinase (as nsk-sd40), 1000 fu (fibronolytic units) of enzyme activity, aframomum melegueta (seed) (6-paradol 12%) (as caloriburn gp), caffeine anhydrous, methyliberine (as dynamine 40%), theacrine (as teacrine 40%), citric acid, natural & artificial flavors, malic acid, soluble corn fiber, sucralose, acesulfame potassium, calcium silicate, silicon dioxide, fd&c blue lake #1", 'Bananas, vegetable oil (coconut oil, corn oil and/or palm oil) sugar, natural banana flavor.', 'Peanuts, wheat flour, sugar, rice flour, tapioca starch, salt, leavening (ammonium bicarbo

In [ ]:
OpenFoodFacts_Demo = pd.read_csv("OpenFoodFacts_Head_Demo.csv")
OpenFoodFacts_Demo.fillna({'product_name':"Unknown"}, inplace=True)


In [35]:
count_vectorizer = CountVectorizer(stop_words='english')
count_vectorizer = CountVectorizer()
sparse_matrix = count_vectorizer.fit_transform(documents)

In [36]:
doc_term_matrix = sparse_matrix.todense()
df = pd.DataFrame(doc_term_matrix, 
                  columns=count_vectorizer.get_feature_names(), 
                  index= ingredient_lists.keys())

In [37]:
print(cosine_similarity(df, df))

[[1.         0.04467671 0.         ... 0.07738232 0.02735878 0.02447044]
 [0.04467671 1.         0.03513642 ... 0.19245009 0.         0.06085806]
 [0.         0.03513642 1.         ... 0.30429031 0.12909944 0.23094011]
 ...
 [0.07738232 0.19245009 0.30429031 ... 1.         0.05892557 0.21081851]
 [0.02735878 0.         0.12909944 ... 0.05892557 1.         0.1118034 ]
 [0.02447044 0.06085806 0.23094011 ... 0.21081851 0.1118034  1.        ]]
